gmmco-shield:
  host: ""
  port: "443"
  clientId: ""
  basePath: "/api"
  path: ""
  method: "GET"

databricks-shield:
  host: ""
  port: "443"
  clientId: ""
  basePath: "/api"
  path: "/upload"
  method: "POST"