


  
gmmco-shield:
  host: "shield-databricks-sys-api-plkk5q.m98vj.sgp-s1.cloudhub.io"
  port: "443"
  clientId: "ca84a09fe412411f9fbd462631040166"
  basePath: "/api"
  path: "/nearmiss"
  method: "GET"

databricks-shield:
  host: "databricks-all-reports-sys-api-dev-plkk5q.m98vj.sgp-s1.cloudhub.io"
  port: "443"
  clientId: "670d3af4d2764a63afdda14e35281964"
  basePath: "/api"
  path: "/upload"
  method: "POST"